var form = new function() {

  this.instance = null;
  this.template = "<h1>{{ title }}</h1><form>{{ inputs }}<hr><button type='reset'>Cancel</button> <button type='submit'>Ok</button></form>";

  this.createInstance = function() {
    var form = document.createElement("div");
    form.setAttribute("class", "modal form");
    document.body.appendChild(form);

    this.instance = form;
  }

  this.renderStringInput = function(json) {
    // fixme: what if value is missing, and add required attribute and connect label for attribute with autogenerated id
    return "<label>" + json.label + "</label><input type='text' value='" + json.value + "' />";
  }

  this.renderIntegerInput = function(json) {
    return "<label>" + json.label + "</label><input type='text' value='" + json.value + "' />";
  }

  this.renderFloatInput = function(json) {
    return "<label>" + json.label + "</label><input type='text' value='" + json.value + "' />";
  }

  this.render = function(json) {

    if (!this.instance)
        this.createInstance();

    var html = this.template;
    html = html.replace("{{ title }}", json.title);

    // create some inputs
    var inputs = "";
    json.inputs.forEach(function(input) {

        switch(input.type) {
            case "float":
            case "integer":
            case "string":
            default:
                inputs += form.renderStringInput(input) + "<br/>";
                break;
        }
    })

    html = html.replace("{{ inputs }}", inputs);

    // connect buttons ok with validation and cancel with destroy

    // overlay the background

    this.instance.innerHTML = html;
  }

  this.destroy = function() {
    if (this.instance)
        document.body.removeChild(this.instance);
    
    this.instance = null;
  }

}

var modals = {
  show: function(json) {

    form.render(json);
  }
}